### ISSUE TITLE
[Bug]: bigger size of mushroom card in sections type of dashboard 

### ISSUE THREAD

**Issue by hrw** [piitaya/lovelace-mushroom#1390]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.
- [X] I have read the state of card mod support (in pin issues) and understand card mod support is not provided in this repository.

### Current Behavior

I use Mushroom cards for quite a while. With HA 2024.3 release I wanted to take a look at their new type of dashboard ("sections"). Updated Mushroom cards to v3.5.2 and started copying items.

Things work as expected but sizes differ in a visible way. I do not know is it HA fault or Mushroom cards.

Masonry type of dashboard:
![obraz](https://github.com/piitaya/lovelace-mushroom/assets/185508/dceb32df-6e6b-4c6e-83b9-7fe5e4fee604)

Sections type of dashboard:
![obraz](https://github.com/piitaya/lovelace-mushroom/assets/185508/589adb24-5456-44cd-b4d9-8749386dd5b1)

### Expected Behavior

I would rather expect the same size. But 'sections' dashboard type is marked as experimental so probably this is the reason.

### Steps To Reproduce

1. create 'sections' dashboard
2. add Mushroom card
3. compare with same card on 'masonry' dashboard

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Firefox
- HA Version: 2024.3.0
- Mushroom: v3.5.2
```

**Comment by L3odalton** [comment]
Same issue for me. 
It is most visible when using two chips-stacks below each other.

**Comment by ptashek** [comment]
Seeing the same with HA 2024.3 + Mushroom 3.5.2 and sections layout.

<img width="399" alt="Screenshot 2024-03-20 at 22 24 11" src="https://github.com/piitaya/lovelace-mushroom/assets/2490317/98e7990e-9321-44a8-8142-b92a0db3157e">


It looks like in the sections layout, there is a parent `div` wrapper around the mushroom card container, which has a `fit-rows` and a `card` class applied to it. That selector defines only one attribute: `height`

```
.card.fit-rows {
    height: calc((var(--row-size, 1)*(var(--grid-row-height) + var(--grid-gap))) - var(--grid-gap));
}
```

When this style is disabled in dev tools, the card renders as expected, and same as in the masonry layout.

**Comment by piitaya** [comment]
@ptashek I fixed your issue with when using `multiline_secondary` options with https://github.com/piitaya/lovelace-mushroom/pull/1402.
It's available in [3.5.4](https://github.com/piitaya/lovelace-mushroom/releases/tag/v3.5.4) release.

@hrw The sections view is still experimental and cards are forced to fit the grid for now so it's not a Mushroom issue. 
As I'm working in the HA front-end team, I can tell you that we are thinking about a way to resize card using the UI.

For now, using this yaml code on the card should fix your issue.
```yaml
layout_options:
   grid_rows: auto
```

**Comment by Depechie** [comment]
@piitaya your suggestion about the grid rows, would this also fix the gap we now have while using chips and the new sections layout? cfr example below.
Because adding
```
card_mod:
  style: |
    ha-card {
      margin-bottom: -66px;
    }
```
to the chips card has no effect.

But I do not understand your ` ayout_options` suggestion, where and how should this be added?

![image](https://github.com/piitaya/lovelace-mushroom/assets/351693/142dc736-4761-4f94-a656-8423a8a7d272)

**Comment by sylv3rblade** [comment]
> ![image](https://private-user-images.githubusercontent.com/351693/322262937-142dc736-4761-4f94-a656-8423a8a7d272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjU4NDcsIm5iZiI6MTcxMzk2NTU0NywicGF0aCI6Ii8zNTE2OTMvMzIyMjYyOTM3LTE0MmRjNzM2LTQ3NjEtNGY5NC1hNjU2LTg0MjNhOGE3ZDI3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxMzMyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGMzZWI0NTQxYzdhMGUwZWU4OTNhN2Y3NmFlMTdmNDIxN2UwMzVjMjk0NGFhOWRiMDQwN2U4YzBhMWNhM2NhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EsRx44Ky9hF3eXTFrA760xPI12U2s97XEpgo8hr3z04)
i have the same issue

![image](https://github.com/piitaya/lovelace-mushroom/assets/467007/5e0b3fcb-aa13-40d5-8557-a99ac6d6a526)
i  found a hacky way to fix it by going into developer tools and override the `--row-height` variable to 33px on the `.container` element that contains the chip cards but i havent found a way to fix this using the card mod (because it's outside the mushroomcard element)
![image](https://github.com/piitaya/lovelace-mushroom/assets/467007/60b6c77e-37fe-4af0-b591-37d2ce9d98da)

the result

![image](https://github.com/piitaya/lovelace-mushroom/assets/467007/01dd6380-f527-4e8c-b8f3-ad964444a286)

**Comment by marcopaggioro** [comment]
Maybe correlated with the fact that the card do not fill orizontally the column even if "fill container" is selected?

![image](https://github.com/piitaya/lovelace-mushroom/assets/24371500/5c5e64e4-b45e-49a9-a61a-6b5dfad81a20)

**Comment by igorsantos07** [comment]
I just came here to report the problem with single-row chip cards, and noticed that `layout_options: { grid_rows: auto }` doesn't solve the issue (it's also not a solution for [empty auto-entites](https://github.com/thomasloven/lovelace-auto-entities/issues/433), although both are related to the variable below).

I did indeed notice that `--row-height` seems to be the culprit - I'm not sure why it is so big, as changing it doesn't _seem_ to affect other cards, since most of them are usually bigger than the 66px in height. That said, that variable should go back to 66px when in edit mode, otherwise the user might have a hard time hitting the edit button.

**Comment by DanDixon** [comment]
> A workaround for this issue with chips is adding them to a vertical-stack with the previous/next card; but this is not feasible in my scenario since I'm using the new Visibility option, and that's not available for sub-cards right now.

As a workaround for this, you could use a conditional card for each 'sub-card' in the vertical-stack (which, as I understand, works the same as the new visibility option).

**Comment by sibbl** [comment]
Just a quick follow-up just in case somebody arrives here with the stably released sections. The following is NOT working anymore:

> For now, using this yaml code on the card should fix your issue.
> 
> ```yaml
> layout_options:
>    grid_rows: auto
> ```

you need to use the following syntax now:

```yaml
grid_options:
  rows: auto
```

(or just use the layout UI to change the value to let the UI generate the code and then change the number to "auto" in the YAML editor of the card)
