### ISSUE TITLE
[Bug]: Mushroom 2.5.1 not loaded on some browsers

### ISSUE THREAD

**Issue by remonegri** [piitaya/lovelace-mushroom#963]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I have a dashboard with various mushroom cards (installed via HACS).
Until this week the mushroom cards have been display without any issue on all devices (laptops, iPhones 6s, 12, 13 and iPads Air 1. generation) and browsers (web browser as well as home assistant app).

Since this week all "iPad Air 1. generation"  show the following error messages where the mushroom cards would sit on the dashboard (both in various web browsers as well as home assistant app).

Error message: "Custom element doesn't exist: mushroom-...-card ..."

On all other devices mushroom cards are displayed correctly.

### Expected Behavior

Mushroom cards are displayed again on all devices and specially again on the iPad Air 1. generation.

### Context

YAML state
```yaml

```

### Environment

```markdown
- Devices: Apple iPad Air 1. generation
- Browser: Safari, Firefox, Edge, Chrome
- HA Version: 2023.1.6
- Mushroom: 2.5.1
```

**Comment by OverZealous** [comment]
I think this [same issue is occurring on a cheap Android device a bunch of folks are testing out](https://www.reddit.com/r/homeassistant/comments/10bsebz/im_really_happy_with_my_bedside_alarm_clock_setup/j53s8r6/). I had to downgrade to `2.4.0` to get them working again.

I would have thought I already had `2.4.1`, I'm pretty aggressive about upgrading, but I couldn't get it to work on 2.4.1 as far as I could tell.

Assuming this is the issue, [the only major difference between those versions is the Romanian language support](https://github.com/piitaya/lovelace-mushroom/compare/v2.4.0...v2.4.1), which doesn't make much sense to me, unless it's some bizarre unicode issue.

**Comment by piitaya** [comment]
Do you have error in the browser console? I know it's difficult to get it in mobile device

**Comment by remonegri** [comment]
> I think this [same issue is occurring on a cheap Android device a bunch of folks are testing out](https://www.reddit.com/r/homeassistant/comments/10bsebz/im_really_happy_with_my_bedside_alarm_clock_setup/j53s8r6/). I had to downgrade to `2.4.0` to get them working again.
> 
> I would have thought I already had `2.4.1`, I'm pretty aggressive about upgrading, but I couldn't get it to work on 2.4.1 as far as I could tell.
> 
> Assuming this is the issue, [the only major difference between those versions is the Romanian language support](https://github.com/piitaya/lovelace-mushroom/compare/v2.4.0...v2.4.1), which doesn't make much sense to me, unless it's some bizarre unicode issue.

Thank you very much for your insights. Much appreciated.
It seems to have something to do with the versioning, as you wrote.

I downgraded mushroom to version 2.4.0 and my iPad Air 1 gen. is now again able to display the mushroom cards properly.
Nevertheless, I hope that future versions would support the iPad Air 1. gen again, as I am also quite aggressive with upgrading. :)

**Comment by remonegri** [comment]
> Do you have error in the browser console? I know it's difficult to get it in mobile device

I am happy to provide, but I do not know how to get the error in the browser console on the iPad.
It seems that downgrading mushroom to version 2.4.0 solved the issue for now.

**Comment by OverZealous** [comment]
I'll see if I can get console logs, but it'll probably be tomorrow before I can get to it.

**Comment by leptians** [comment]
I have the same problem with version 2.5.1 running on Lenovo Smart Clock 2. Downgrade to 2.4.1 works fine

**Comment by bitcrumb** [comment]
Seeing the same here. Since last update the mushroom cards are showing the "Custom element doesn't exist: mushroom-...-card ..." on my iPad 2 as well.

Would be a shame if this can't be fixed, since this way my old devices still have a use being mounted against the wall 🙁

**Comment by bitcrumb** [comment]
I'm seeing an unhandled promise rejection error, but hard to debug where it comes from due to the minified code.

![Screenshot 2023-01-21 at 09 03 47](https://user-images.githubusercontent.com/135126/213858168-db6d3b50-c7b4-4862-bf7a-ee247975acbc.png)

**Comment by Luth1ng** [comment]
I'm also having this issue since last 2.5.1 update on my iPad Air Gen1.

The error from browser console:
```
[Error] Unhandled Promise Rejection: http://192.168.1.50:8123/hacsfiles/lovelace-mushroom/mushroom.js?hacstag=444350375251
	(anonymous function)
	rejectPromise
```

I'm available for debugging if needed

**Comment by wtrdk** [comment]
Same here. I'm not able to access the browser console, but I attached 2 screenshots of the same lovelace screen. The one displaying correctly is an iPad Air 2 running OS 15.7.2
The one displaying the errors is an iPad Air 1 running OS 12.5.5
![IMG_1606E971C4FD-1](https://user-images.githubusercontent.com/4569244/213865007-3259f850-69fd-4894-a5fe-a2d0b9a8b4c7.jpeg)
![IMG_512350897118-1](https://user-images.githubusercontent.com/4569244/213865008-65041b0b-bce3-46da-87b7-2cb4ab2c0bec.jpeg)

**Comment by piitaya** [comment]
I'm trying to reproduce the issue. You can downgrade until I or somebody find a fix. Thanks for sharing debug logs 🙏

**Comment by PH89** [comment]
Can confirm this bug on iPad Mini 3 running iOS 12.5.6

**Comment by dado1990** [comment]
Same problem on my iPad Air 1, how to downgrade?

**Comment by benchristian88** [comment]
Same issue on tizen 6.0 on Samsung family hub smart fridge.

**Comment by jbeardon** [comment]
Same issue on Amazon Fire 7 Gen 9 (2019)
Exists in both Wallpanel browser and the HA Companion app.

**Comment by tadly** [comment]
Same on my Fire HD 8 Tab.
I got 2.4.1 working again though so not quite the same as OP.

I did a "clean" install of the addon by deleting it on the filesystem and then reinstalling through HACS (selecting 2.4.1)

Tested with the latest versions of [Wallpanel](https://wallpanel.app/) and [Fullykiosk](https://www.fully-kiosk.com/), both of which didn't work with 2.5.1.

**Comment by jbeardon** [comment]
> Same on my Fire HD 8 Tab. I got 2.4.1 working again though so not quite the same as OP.
> 
> I did a "clean" install of the addon by deleting it on the filesystem and then reinstalling through HACS (selecting 2.4.1)
> 
> Tested with the latest versions of [Wallpanel](https://wallpanel.app/) and [Fullykiosk](https://www.fully-kiosk.com/), both of which didn't work with 2.5.1.

Which generation of HD8? I've got 2 HD8 Gen 10 (2020) tabs and they are unaffected.

**Comment by tadly** [comment]
> Which generation of HD8? I've got 2 HD8 Gen 10 (2020) tabs and they are unaffected.

Also 10th gen with Fire OS 7.3.1.5

**Comment by jbeardon** [comment]
> 

Hmm - mine are only a couble of subversions different - 7.3.1.9

**Comment by piitaya** [comment]
You can try the `2.5.2` version : https://github.com/piitaya/lovelace-mushroom/releases/tag/v2.5.2
It's available as beta in HACS.

**Comment by jbeardon** [comment]
> You can try the `2.5.2` version : https://github.com/piitaya/lovelace-mushroom/releases/tag/v2.5.2 It's available as beta in HACS.

Can confirm 2.5.2 beta has corrected the issue on the Fire HD 7 2019 running FireOS 7.3.1.6

Thank you!

**Comment by bitcrumb** [comment]
Can confirm as well! Thank you 🙏🏻

**Comment by OverZealous** [comment]
Confirm fixed on the Lenovo Smart Clocks. Looks like Babel needs the [Nullish Coalescing Operator plugin](https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator) to fix `??` usage.

**Comment by leptians** [comment]
Same here, can confirm fixed on Lenovo Smart Clock 2 with `2.5.2`

**Comment by gralin** [comment]
Same here, fixed with `2.5.2` on NSPanel Pro with Android 8.1

**Comment by remonegri** [comment]
Same here. I can confirm the fix works for Apple iPad Air 1. Gen.
@piitaya: Thank you very much for the quick fix. Very much appreciated. 🙏🏻

**Comment by lasharor** [comment]
After updating I have this problem now on Chrome on my desktop. Working fine on my iPhone.

**Comment by bkr1969** [comment]
I'm having the same issue on iPhone 13 (iOS 16.2).  Only with the mushroom-select-card.  
"Custom element doesn't exist..."

**Comment by gmariotti** [comment]
Apologies for commenting on a closed issue, but I'm still having this problem when casting to a Nest Hub. `custom:mushroom-light-card` are not rendered at all and only downgrading to 2.4.1 fixes it

**Comment by piitaya** [comment]
I just tested on Nest Hub and I have no issues 😞

**Comment by gmariotti** [comment]
@piitaya any idea how I could debug it myself?

**Comment by piitaya** [comment]
No problem, open an another issue if there is need to try to debug it to avoid using this one (because it's closed)

**Comment by TomNOYB** [comment]
I have this issue after the latest v4.1.0 update on the iPad mini 2. It was working fine before and other devices still run normal.
Custom element doesn't exist: mushroom-light-card

**Comment by Hjlfmir** [comment]
Hello. Same issue with NSPanel Pro with 4.2.0 FW (with Home Assistant native app through F-Droid now included in NSPanel Pro).
I just have a red care with "!"
